# Generated by Django 5.1.5 on 2025-01-31 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_created_date_alter_post_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 5, 27, 53, 23155, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 5, 27, 53, 24245, tzinfo=datetime.timezone.utc)),
        ),
    ]
